# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: mysql2
  database: bbs
  pool: 5
  username: root
  encoding: utf8
  host: localhost

production:
  adapter: mysql2
  database: bbs_production
  pool: 5
  username: root
  encoding: utf8
  host: localhost
